version: '3.4'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=blog
      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD="1"
    env_file: .env


  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=blog
      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1
#    env_file: .env
    depends_on:
      - db

